# Generated by Django 5.2.4 on 2025-07-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='step_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('pinCode', models.CharField(max_length=50)),
            ],
        ),
    ]
